config/routes.rb
Rails.application.routes.draw do
 
  resources :sponsors
  resources :prizes
  get 'privacy/index', :as => :privacy
  get 'help/index', :as => :help

  resources :bets
  resources :matches
  resources :configs
  resources :groups
  resources :teams
  resources :users
  get '/overview/index'
  get '/sessions/login'
  
  get '/overview/bet', :as => :user_bet
  
  get '/matches/:id/random_bets'  => 'matches#random_bets', :as => :random_bets
  get '/matches/:id/random_result'  => 'matches#random_result', :as => :random_result
  
  get '/users/:id/champion'  => 'users#champion', :as => :user_champion
  get '/users/:id/top_goal_scorer'  => 'users#top_goal_scorer', :as => :user_top_goal_scorer
  put '/users/:id/champion'  => 'users#update_champion', :as => :user_champion_edit 
  put '/users/:id/top_goal_scorer'  => 'users#update_top_goal_scorer', :as => :user_top_goal_scorer_edit
  
  get '/teams/:id/players' => 'teams#players', :as => :team_players
  
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/signin_facebook' => 'sessions#new_facebook', :as => :signin_facebook
  get '/signin_google' => 'sessions#new_google', :as => :signin_google 
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'overview#index'
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :match
  belongs_to :user
    
  validates :user, uniqueness: { scope: :match}
  validates :match, :user, :bet, :bet_left_score, :bet_right_score , presence: true  
  validates :bet, :inclusion => {:in => [-1,0,1]}  
  validate :validate_on_bet
  #before_destroy :validate_before_destroy    

  attr_accessor :caller
  
  def win?       
    if self.bet == self.match.result
      return true
    else
      return false
    end
  end
  
  def owner?(user)
    if self.user.id == user.id
      return true
    else
      return false
    end
  end
  
  def public?
    return self.match.lock?      
  end
  
  def pts_final_result
    score = 0
    if self.bet == self.match.result
      score = Config.find_by_key('BET_MAIN_FINAL_RESULT_SCORE').value.to_i    
    end
    return score
  end
  
  def pts_left_team
    score = 0
    if self.bet_left_score == self.match.left_score
      score = Config.find_by_key('BET_MAIN_LEFT_TEAM_SCORE').value.to_i    
    end
    return score
  end
  
  def pts_right_team
    score = 0
    if self.bet_right_score == self.match.right_score
      score = Config.find_by_key('BET_MAIN_RIGHT_TEAM_SCORE').value.to_i    
    end
    return score
  end
  
  def pts_yellow_card
    score = 0
    if self.yellow_card == self.match.yellow_card
      if self.yellow_card?        
        score = Config.find_by_key('BET_MAIN_YELLOW_CARD_SCORE').value.to_i
      else
        score = Config.find_by_key('BET_MAIN_NO_YELLOW_CARD_SCORE').value.to_i
      end      
    end
    return score
  end
  
  def pts_red_card
    score = 0
    if self.red_card == self.match.red_card
      if self.red_card?        
        score = Config.find_by_key('BET_MAIN_RED_CARD_SCORE').value.to_i
      else
        score = Config.find_by_key('BET_MAIN_NO_RED_CARD_SCORE').value.to_i
      end      
    end
    return score
  end
  
  def pts_own_goal
    score = 0
    if self.own_goal == self.match.own_goal
      if self.own_goal       
        score = Config.find_by_key('BET_MAIN_OWN_GOAL_SCORE').value.to_i
      else
        score = Config.find_by_key('BET_MAIN_NO_OWN_GOAL_SCORE').value.to_i
      end      
    end
    return score
  end
  
  def pts_extra_time
    score = 0
    if self.extra_time == self.match.extra_time
        if self.extra_time?         
        score = Config.find_by_key('BET_MAIN_EXTRA_TIME_SCORE').value.to_i
      else
        score = Config.find_by_key('BET_MAIN_NO_EXTRA_TIME_SCORE').value.to_i
      end      
    end
    return score
  end
  
  def pts_penalty
    score = 0
    if self.penalty == self.match.penalty
        if self.penalty?        
        score = Config.find_by_key('BET_MAIN_PENALTY_SCORE').value.to_i
      else
        score = Config.find_by_key('BET_MAIN_NO_PENALTY_SCORE').value.to_i
      end      
    end
    return score
  end
  
  def bonus_champion?
    if self.match.final? && self.match.knockout?
      champion = self.user.champion
      if !champion.nil?
        if champion.id == self.match.left.id || champion.id == self.match.right.id
          return true
        end
      end      
    end
    return false
  end
  
  def pts_bonus_champion(main_score)                  
    if bonus_champion?
      multiply = Config.find_by_key('BET_BONUS_CHAMPION_MULTIPLY').value.to_f    
      bonus_score = (main_score * multiply).to_i      
      return bonus_score
    else
      return 0  
    end             
  end
  
  def pts      
        
    if self.match.result.nil?
      return 0
    end
    
    main_score = pts_final_result + pts_left_team + pts_right_team + pts_yellow_card + pts_red_card + pts_own_goal
    if self.match.knockout?
      main_score = main_score + pts_extra_time + pts_penalty
    end           
    
    bonus_score = pts_bonus_champion(main_score)

    #logger.info 'main_score : '+main_score.to_s
    #logger.info 'bonus_score : '+bonus_score.to_s
    
    return main_score+bonus_score
  end 
  
  def self.random(caller, user, match)        
    logger.info "Random bets for user #{user.name}"  
    if !Bet.exists?(user: user, match: match)
      logger.info "Auto generate bet."
      Bet.create(user: user, match: match \
      , caller: caller \
      , bet: [-1,0,1].shuffle.first \
      , bet_left_score: [0,1,2,3].shuffle.first \
      , bet_right_score: [0,1,2,3].shuffle.first \
      , yellow_card: [true,false].shuffle.first \
      , red_card: [true,false].shuffle.first \
      , own_goal: [true,false].shuffle.first \
      , extra_time: [true,false].shuffle.first \
      , penalty: [true,false].shuffle.first)
    else
      logger.info "User already bet."
    end
    
  end
  
  private  
  def validate_before_destroy
    if self.match.lock?                 
      errors.add(:bet,"not allowed (match is locked on #{self.match.start})")
      throw(:abort)
    end
  end
  
  def validate_on_bet    
                
    if self.match.lock?
      if !self.caller.nil? && self.caller.admin?
        logger.info "Caller from admin any bet can created. (skip validate match lock)"
      else
        logger.info "Caller from user any bet after match lock is prohibited."
        errors.add(:bet,"not allowed (match is locked on #{self.match.start})")
        throw(:abort)           
      end      
    end
    
    if !new_record? && self.match_id_changed?
      errors.add(:match,"can't change")
    end
    if !new_record? && self.user_id_changed?
      errors.add(:user,"can't change")
    end    
    if self.match.knockout?
      if self.bet == 0
        errors.add(:bet,"can't be zero in knockout stage")
      end
    end
  end
  
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :require_login_permission_and_admin, except: [:show, :new, :edit, :create, :update]
  before_action :require_login_permission, only: [:show, :new, :edit, :create, :update]
  before_action :set_bet, only: [:show, :edit, :update, :destroy]

  # GET /bets
  # GET /bets.json
  def index        
    if params[:match].present? && params[:user].present?
        @bets = Bet.where("match_id = ?","#{params[:match]}").where("user_id = ?","#{params[:user]}").order(:match_id).paginate(:page => params[:page], :per_page => 100)
    else
      if params[:match].present?
        @bets = Bet.where("match_id = ?","#{params[:match]}").order(:match_id).paginate(:page => params[:page], :per_page => 100)
      else
        if params[:user].present?
          @bets = Bet.where("user_id = ?","#{params[:user]}").order(:match_id).paginate(:page => params[:page], :per_page => 100)
        else
          @bets = Bet.order(:match_id).paginate(:page => params[:page], :per_page => 100)
        end 
      end
    end        
    #@bets.sort_by{|b| [b.match.start]}    
  end

  # GET /bets/1
  # GET /bets/1.json
   def show
    respond_to do |format|
      if @bet.public?
        if params[:modal].present?
          format.html { render :show_modal, layout: false }
        else
          format.html { render :show }
        end
      else
        format.html { redirect_to '/404' }
      end
    end
  end

  # GET /bets/new
  def new                         
    @bet = Bet.new
    
    if params[:match].present?
      @bet.match = Match.find(params[:match])        
    end
        
    @bet.user = User.find(session[:user_id])
    @bet_data = bet_result_data(@bet)    
    @modal = params[:modal].present? ? true:false  
                        
    respond_to do |format|
      if @modal          
        format.html {render :new, layout: false}
      else 
        format.html {render :new}
      end
    end
           
  end
  
  # GET /bets/1/edit
  def edit    
        
    @user = User.find(session[:user_id])
    @bet.user = @user    
    @bet_data = bet_result_data(@bet)  
    @modal = params[:modal].present? ? true:false
     
    respond_to do |format|
      if @modal
        format.html {render :edit, layout: false}
      else
        format.html {render :edit}
      end
    end

  end

  # POST /bets
  # POST /bets.json
  def create
    @bet = Bet.new(bet_params)    
    @bet.user = User.find(session[:user_id])
    @modal = params[:modal].present? ? true:false
    
    respond_to do |format|
      if @bet.save
        if @modal
          format.html { redirect_to :root }          
        else
          format.html { redirect_to @bet, notice: 'Bet was successfully created.' }  
        end                         
        format.json { render :show, status: :created, location: @bet }
      else
        if @modal
          format.html { redirect_to :root }  
        else
          @bet_data = bet_result_data(@bet)
          format.html { render :new }
          format.json { render json: @bet.errors, status: :unprocessable_entity }
        end                
      end
    end
  end

  # PATCH/PUT /bets/1
  # PATCH/PUT /bets/1.json
  def update
                                       
    respond_to do |format|
      @modal = params[:modal].present? ? true:false
      if !@bet.owner?(User.find(session[:user_id]))
        format.html { redirect_to '/404' } 
      end
      
      if @bet.update(bet_params)
        if @modal
          format.html { redirect_to :root }
        else
          format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        end
        format.json { render :show, status: :ok, location: @bet }
      else
        if @modal
          format.html { redirect_to :root }  
        else
          @bet_data = bet_result_data(@bet)
          format.html { render :edit }
          format.json { render json: @bet.errors, status: :unprocessable_entity }
        end 
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy                    
    respond_to do |format|      
      if @bet.public?  
        format.html { redirect_to '/404' } 
      end      
      @bet.destroy            
      format.html { redirect_to bets_url, notice: 'Bet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.find(params[:id])              
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_params
      params.require(:bet).permit(:match_id, :user_id, :bet, :bet_left_score, :bet_right_score, :yellow_card, :red_card, :own_goal, :extra_time, :penalty)
    end
    
    def bet_result_data(bet)
        if bet.match.nil?
          return [[-1,'Left'],[0,'Draw'],[1,'Right']]
        else
          if bet.match.knockout?
            return [[-1,bet.match.left.nil? ? ('Left'):(bet.match.left.name)],[1,bet.match.right.nil? ? ('Right'):(bet.match.right.name)]]
          else
            return [[-1,bet.match.left.nil? ? ('Left'):(bet.match.left.name)],[0,'Draw'],[1,bet.match.right.nil? ? ('Right'):(bet.match.right.name)]] 
          end  
        end
        
    end
    
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_with(model: bet, local: true) do |form| %>
<% if bet.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

	<ul>
		<% bet.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="panel panel-default">
	<div class="panel-heading">
		Main
	</div>
	<div class="panel-body">
			
		<div class="field">			
			<%= form.label "Player : " %>			
			<%= bet.user.name %>			
			<%= form.hidden_field :user_id %>									
		</div>
												
		<div class="field">			
			<%= form.label "Match : " %>
			<% if @modal %>
				<%= bet.match.title %>
				<%= form.hidden_field :match_id %>
				<%= form.hidden_field :user_id %>
			<% else %>
				<%= form.collection_select(:match_id, Match.all, :id, :title, {prompt: true}) %>
				<%= form.hidden_field :user_id %>
			<% end %>									
		</div>
					
		<div class="field">
			<%= form.label "ผลการแข่งขัน (#{Config.find_by_key('BET_MAIN_FINAL_RESULT_SCORE').value} คะแนน) : " %>			
			<%= form.collection_select :bet, @bet_data, :first, :last, prompt: true %>			
		</div>

		<div class="field">
			<%= form.label display_label_bet_left_team(bet) %>
			<%= form.number_field :bet_left_score, id: :match_left_score %>
		</div>

		<div class="field">
			<%= form.label display_label_bet_right_team(bet) %>
			<%= form.number_field :bet_right_score, id: :match_right_score %>
		</div>
		
		<div class="field">
			<%= form.label "มีใบเหลืองเกิดขึ้นมากกว่า  #{Config.find_by_key('BET_MAIN_YELLOW_CARD_CONDITION').value} ใบ หรือไม่ ? (#{Config.find_by_key('BET_MAIN_YELLOW_CARD_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_YELLOW_CARD_SCORE').value} คะแนน): " %>
			<%= form.check_box :yellow_card, id: :yellow_card %>
		</div>

		<div class="field">
			<%= form.label "มีใบแดงเกิดขึ้น หรือไม่ ? (#{Config.find_by_key('BET_MAIN_RED_CARD_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_RED_CARD_SCORE').value} คะแนน): " %>
			<%= form.check_box :red_card, id: :red_card %>
		</div>
		
		<div class="field">
			<%= form.label "มีการทำประตูตัวเองเกิดขึ้น หรือไม่ ? (#{Config.find_by_key('BET_MAIN_OWN_GOAL_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_OWN_GOAL_SCORE').value} คะแนน): " %>
			<%= form.check_box :own_goal, id: :own_goal %>
		</div>
		
		<% if bet.match.knockout? %>
			<div class="field">
				<%= form.label "มีการต่อเวลาพิเศษ หรือไม่ ? (#{Config.find_by_key('BET_MAIN_EXTRA_TIME_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_EXTRA_TIME_SCORE').value} คะแนน): " %>
				<%= form.check_box :extra_time, id: :extra_time %>
			</div>		
			<div class="field">
				<%= form.label "มีการตัดสินหาผู้ชนะด้วยวิธีการยิงจุดโทษ หรือไม่ ? (#{Config.find_by_key('BET_MAIN_PENALTY_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_PENALTY_SCORE').value} points): " %>
				<%= form.check_box :penalty, id: :penalty %>
			</div>
		<% end %>

		
	</div>
</div>

<div class="actions">					
	<% if @modal %>
		<%= hidden_field_tag :modal, @modal %>
	<% end %>	
	<%= form.submit %>
</div>
<% end %>

app/views/bets/_search.html.erb
<%= form_tag(bets_path, method: "get") do |form| %>
<div class="row">	
	<div class="col-md-4">
		<div class="form-group">
			<%= label_tag(:match) %>
			<%= select_tag :match, options_from_collection_for_select(Match.all, "id", "display_title"), :class=>'form-control', include_blank: true %>
		</div>
	</div>
	<div class="col-md-4">
		<div class="form-group">
			<%= label_tag(:user) %>
			<%= select_tag :user, options_from_collection_for_select(User.all, "id", "name"), :class=>'form-control', include_blank: true %>
		</div>
	</div>	
</div>

<div class="row">
	<div class="col-md-12">
		<div class="actions">
			<%= submit_tag("Search", :class=>'btn btn-default') %>
			<%= submit_tag("Clear", :class=>'btn btn-default',:type => "reset") %>
		</div>
	</div>
</div>

<% end %>

app/views/bets/edit.html.erb
<h1>Editing Bet</h1>

<%= render 'form', bet: @bet %>

<% if !@modal %>
	<%= link_to 'Show', @bet %> |
	<%= link_to 'Back', bets_path %>
<% end %>

app/views/bets/index.html.erb
<p id="notice">
	<%= notice %>
</p>

<h1>Bets</h1>

<%= render 'search' %>

<div class="row">
	<div class="col-md-12">
		<table class="table table-hover">
			<thead>
			    <tr>
			      <th>Match</th>
			      <th>Kick-off</th>
			      <th>User</th>
			      <th>Result</th>			      
			      <th>Bet</th>
			      <th>Score</th>
			      <th>Win?</th>			      			      
			      <th colspan="3"></th>
			    </tr>
			</thead>

			<tbody>
				<% @bets.each do |bet| %>
				<tr>
					<td><%= display_match_description(bet.match) %></td>
					<td><%= bet.match.start.strftime("%-d %-b %Y %H:%M:%S") %></td>
					<td><%= display_user(bet.user) %></td>
					<td><%= display_match_result(bet.match) %></td>        			
        			<td><%= display_your_bet(bet) %></td>        			        				
        			<td><%= display_your_score(bet) %></td>
        			<td><%= display_bet_result_icon(bet) %></td>        			
        			<td> <%= link_to 'Show', bet , :class => 'btn btn-default'%>
					<%= link_to 'Edit', edit_bet_path(bet,:admin=>true) , :class => 'btn btn-default'%>
					<%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-danger'%> </td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<%= will_paginate @bets %>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<%= link_to 'New Bet', new_bet_path , :class => 'btn btn-primary' %>
	</div>
</div>

app/views/bets/new.html.erb
<h1>New Bet</h1>

<%= render 'form', bet: @bet %>

<% if !@modal %>
	<%= link_to 'Back', bets_path %>
<% end %>

app/views/bets/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<div class="panel panel-default">
	<div class="panel-heading">
		Main
	</div>
	<div class="panel-body">
		
		<table class="table table-bordered">
  			<tr class="active">
  				<th class="text-center">Bet</th>
  				<th class="text-center">Your bet</th>
  				<th class="text-center">Match result</th>
  				<th class="text-center">PTS</th>
  			</tr>
  			<tr>
  				<td><%= "Result (#{Config.find_by_key('BET_MAIN_FINAL_RESULT_SCORE').value} points)" %></td>
  				<td class="text-center"><%= display_your_bet(@bet) %></td>
  				<td class="text-center"><%= display_match_result(@bet.match) %></td>
  				<td class="text-center"><%= @bet.pts_final_result %></td>
  			</tr>
  			<tr>
  				<td><%= "Left Score (#{Config.find_by_key('BET_MAIN_LEFT_TEAM_SCORE').value} points)" %></td>
  				<td class="text-center"><%= @bet.bet_left_score %></td>
  				<td class="text-center"><%= @bet.match.left_score %></td>
  				<td class="text-center"><%= @bet.pts_left_team %></td>
  			</tr>
  			<tr>
  				<td><%= "Right Score (#{Config.find_by_key('BET_MAIN_RIGHT_TEAM_SCORE').value} points)" %></td>
  				<td class="text-center"><%= @bet.bet_right_score %></td>
  				<td class="text-center"><%= @bet.match.right_score %></td>
  				<td class="text-center"><%= @bet.pts_right_team %></td>
  			</tr>
  			<tr>
  				<td><%= "#{:yellow_card}? (Yes/No) more then #{Config.find_by_key('BET_MAIN_YELLOW_CARD_CONDITION').value} cards (#{Config.find_by_key('BET_MAIN_YELLOW_CARD_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_YELLOW_CARD_SCORE').value} points)" %></td>
  				<td class="text-center"><%= @bet.yellow_card %></td>
  				<td class="text-center"><%= @bet.match.yellow_card %></td>
  				<td class="text-center"><%= @bet.pts_yellow_card %></td>
  			</tr>
  			<tr>
  				<td><%= "#{:red_card}? (Yes/No) (#{Config.find_by_key('BET_MAIN_RED_CARD_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_RED_CARD_SCORE').value} points)" %></td>
  				<td class="text-center"><%= @bet.red_card %></td>
  				<td class="text-center"><%= @bet.match.red_card %></td>
  				<td class="text-center"><%= @bet.pts_red_card %></td>
  			</tr>
  			<tr>
  				<td><%= "#{:own_goal}? (Yes/No) (#{Config.find_by_key('BET_MAIN_OWN_GOAL_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_OWN_GOAL_SCORE').value} points)" %></td>
  				<td class="text-center"><%= @bet.own_goal %></td>
  				<td class="text-center"><%= @bet.match.own_goal %></td>
  				<td class="text-center"><%= @bet.pts_own_goal %></td>
  			</tr>
  			<% if @bet.match.knockout? %>
	  			<tr>
	  				<td><%= "#{:extra_time}? (Yes/No) (#{Config.find_by_key('BET_MAIN_EXTRA_TIME_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_EXTRA_TIME_SCORE').value} points)" %></td>
	  				<td class="text-center"><%= @bet.extra_time %></td>
	  				<td class="text-center"><%= @bet.match.extra_time %></td>
	  				<td class="text-center"><%= @bet.pts_extra_time %></td>
	  			</tr>
	  			<tr>
	  				<td><%= "#{:penalty} shootout after a drawn match? (Yes/No) (#{Config.find_by_key('BET_MAIN_PENALTY_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_PENALTY_SCORE').value} points)" %></td>
	  				<td class="text-center"><%= @bet.penalty %></td>
	  				<td class="text-center"><%= @bet.match.penalty %></td>
	  				<td class="text-center"><%= @bet.pts_penalty %></td>
	  			</tr>
  			<% end %>
  			<tr class="active">
  				<td><strong>Total<strong></td>
  				<td></td>
  				<td></td>
  				<td class="text-center"><strong><%= @bet.pts %><strong></td>
  			</tr>
		</table>

	</div>
</div>
<% if !@modal %>
<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>
<% end %>

app/views/bets/show_modal.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Main
	</div>
	<div class="panel-body">
		
		<table class="table table-bordered">
  			<tr class="active">
  				<th class="text-center">Bet</th>
  				<th class="text-center">Bet</th>
  				<th class="text-center">Result</th>
  				<th class="text-center">PTS</th>
  			</tr>
  			<tr>
  				<td><%= "Result (#{Config.find_by_key('BET_MAIN_FINAL_RESULT_SCORE').value} points)" %></td>
  				<td class="text-center"><%= display_your_bet(@bet) %></td>
  				<td class="text-center"><%= display_match_result(@bet.match) %></td>
  				<td class="text-center"><%= @bet.pts_final_result %></td>
  			</tr>
  			<tr>
  				<td><%= "Left Score (#{Config.find_by_key('BET_MAIN_LEFT_TEAM_SCORE').value} points)" %></td>
  				<td class="text-center"><%= @bet.bet_left_score %></td>
  				<td class="text-center"><%= @bet.match.left_score %></td>
  				<td class="text-center"><%= @bet.pts_left_team %></td>
  			</tr>
  			<tr>
  				<td><%= "Right Score (#{Config.find_by_key('BET_MAIN_RIGHT_TEAM_SCORE').value} points)" %></td>
  				<td class="text-center"><%= @bet.bet_right_score %></td>
  				<td class="text-center"><%= @bet.match.right_score %></td>
  				<td class="text-center"><%= @bet.pts_right_team %></td>
  			</tr>
  			<tr>
  				<td><%= "#{:yellow_card}? (Yes/No) more then #{Config.find_by_key('BET_MAIN_YELLOW_CARD_CONDITION').value} cards (#{Config.find_by_key('BET_MAIN_YELLOW_CARD_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_YELLOW_CARD_SCORE').value} points)" %></td>
  				<td class="text-center"><%= @bet.yellow_card %></td>
  				<td class="text-center"><%= @bet.match.yellow_card %></td>
  				<td class="text-center"><%= @bet.pts_yellow_card %></td>
  			</tr>
  			<tr>
  				<td><%= "#{:red_card}? (Yes/No) (#{Config.find_by_key('BET_MAIN_RED_CARD_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_RED_CARD_SCORE').value} points)" %></td>
  				<td class="text-center"><%= @bet.red_card %></td>
  				<td class="text-center"><%= @bet.match.red_card %></td>
  				<td class="text-center"><%= @bet.pts_red_card %></td>
  			</tr>
  			<tr>
  				<td><%= "#{:own_goal}? (Yes/No) (#{Config.find_by_key('BET_MAIN_OWN_GOAL_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_OWN_GOAL_SCORE').value} points)" %></td>
  				<td class="text-center"><%= @bet.own_goal %></td>
  				<td class="text-center"><%= @bet.match.own_goal %></td>
  				<td class="text-center"><%= @bet.pts_own_goal %></td>
  			</tr>
  			<% if @bet.match.knockout? %>
	  			<tr>
	  				<td><%= "#{:extra_time}? (Yes/No) (#{Config.find_by_key('BET_MAIN_EXTRA_TIME_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_EXTRA_TIME_SCORE').value} points)" %></td>
	  				<td class="text-center"><%= @bet.extra_time %></td>
	  				<td class="text-center"><%= @bet.match.extra_time %></td>
	  				<td class="text-center"><%= @bet.pts_extra_time %></td>
	  			</tr>
	  			<tr>
	  				<td><%= "#{:penalty} shootout after a drawn match? (Yes/No) (#{Config.find_by_key('BET_MAIN_PENALTY_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_PENALTY_SCORE').value} points)" %></td>
	  				<td class="text-center"><%= @bet.penalty %></td>
	  				<td class="text-center"><%= @bet.match.penalty %></td>
	  				<td class="text-center"><%= @bet.pts_penalty %></td>
	  			</tr>
  			<% end %>
  			<tr class="active">
  				<td><strong>Total<strong></td>
  				<td class="text-center">Bonus</td>
  				<td class="text-center"><%= @bet.bonus_champion? ? "x #{Config.find_by_key('BET_BONUS_CHAMPION_MULTIPLY').value.to_f*2}":"-"%></td>
  				<td class="text-center"><strong><%= @bet.pts %><strong></td>
  			</tr>
		</table>

	</div>
</div>