config/routes.rb
Rails.application.routes.draw do
 
  resources :sponsors
  resources :prizes
  get 'privacy/index', :as => :privacy
  get 'help/index', :as => :help

  resources :bets
  resources :matches
  resources :configs
  resources :groups
  resources :teams
  resources :users
  get '/overview/index'
  get '/sessions/login'
  
  get '/overview/bet', :as => :user_bet
  
  get '/matches/:id/random_bets'  => 'matches#random_bets', :as => :random_bets
  get '/matches/:id/random_result'  => 'matches#random_result', :as => :random_result
  
  get '/users/:id/champion'  => 'users#champion', :as => :user_champion
  get '/users/:id/top_goal_scorer'  => 'users#top_goal_scorer', :as => :user_top_goal_scorer
  put '/users/:id/champion'  => 'users#update_champion', :as => :user_champion_edit 
  put '/users/:id/top_goal_scorer'  => 'users#update_top_goal_scorer', :as => :user_top_goal_scorer_edit
  
  get '/teams/:id/players' => 'teams#players', :as => :team_players
  
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/signin_facebook' => 'sessions#new_facebook', :as => :signin_facebook
  get '/signin_google' => 'sessions#new_google', :as => :signin_google 
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'overview#index'
end

app/models/user.rb
class User < ApplicationRecord

  belongs_to :champion, :class_name => 'Team', :foreign_key => 'team_id', optional: true
  
  validates :uid, uniqueness: true
  validates :top_goal_scorer, length: { maximum: 64 }
  validates :nickname, :party, length: { maximum: 32 }
    
  def display_payment
    if self.payment.nil?
       return 'Wait'
    else
       return self.payment ? 'Approve':'Wait'
    end
  end
  
  def display_name
    if self.nickname.nil?
      return self.name
    else
      return "#{self.name} (#{self.nickname})"
    end
  end  
    
  def admin?    
    return self.admin
  end    
    
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
        user.name = auth['info']['name'] || ""
        user.email = auth['info']['email'] || ""
        user.image = auth['info']['image'] || ""
      end
      if ENV['ROOT_UID']
        if ENV['ROOT_UID'].eql?(user.uid)
        user.admin = true
        else
        user.admin = false
        end
      end
    end
  end

  def pts
    total = 0
    bets = Bet.where(user: self)    
    bets.each do |bet|    
      total = total + bet.pts      
    end
    return total
  end
  
  def p
    total = 0
    matches = Match.all    
    matches.each do |match| 
      if !match.result.nil?   
        total = total + 1
      end      
    end
    return total
  end
  
  def rank
    standings = User.all.sort_by{|u| [-u.pts.to_i,u.id]}
    standings.each_with_index do |player, index|
       if player.id == self.id
         return index + 1
       end
    end
    return -1
  end
  
  def ratio_win    
    count = 0
    win = 0
    bets = Bet.where(user: self)    
    bets.each do |bet|    
      if bet.match.result.nil?        
        next                  
      end          
      if bet.win?
        win = win +1      
      end      
      count = count + 1      
    end
    
    if count == 0
      return 'n/a'
    else
      return win*100/count
    end
        
  end
  
  def continuous_win
    win = 0
    bets = Bet.where(user: self).sort_by{|b| [b.match.start]}    
    bets.each do |bet|    
      if bet.match.final?        
        if bet.win?
          win = win + 1
        else
          win = 0
        end                   
      end                      
    end
    return win
  end
  
  def continuous_loss
    loss = 0
    bets = Bet.where(user: self).sort_by{|b| [b.match.start]}    
    bets.each do |bet|    
      if bet.match.final?        
        if !bet.win?
          loss = loss + 1
        else
          loss = 0
        end                   
      end                      
    end
    return loss
  end
  
  def prizes
    return @prizes = Prize.where("user_id = ?",self)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  before_action :require_login_permission_and_admin, except: [:show, :champion, :top_goal_scorer, :update_champion, :update_top_goal_scorer]
  before_action :require_login_permission, only: [:show, :champion, :top_goal_scorer, :update_champion, :update_top_goal_scorer]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :champion, :top_goal_scorer]

  def users_to_csv(users)   
    csv_string = CsvShaper::Shaper.encode do |csv|      
      csv.headers do |header|
        header.columns :provider, :uid, :name, :nickname, :gender, :email, :admin, :payment, :party, :team_id, :top_goal_scorer, :win_ratio, :win_continuous, :loss_continuous
      end      
      users.each do |user|
        csv.row do |row|
          row.cell :provider, user.provider
          row.cell :uid, user.uid
          row.cell :name, user.name
          row.cell :nickname, user.nickname
          row.cell :gender, user.gender
          row.cell :email, user.email
          row.cell :admin, user.admin          
          row.cell :payment, user.payment
          row.cell :party, user.party.blank? ? "n/a":user.party
          row.cell :team_id, user.team_id.blank? ? "n/a":user.champion.name
          row.cell :top_goal_scorer, user.top_goal_scorer.blank? ? "n/a":user.top_goal_scorer          
          row.cell :win_ratio, user.ratio_win
          row.cell :win_continuous, user.continuous_win
          row.cell :loss_continuous, user.continuous_loss                                                                        
        end
      end
    end
    return csv_string
  end
  
  # GET /users
  # GET /users.json
  def index
        
    # @users = User.all   
    if params[:name].present? && params[:uid].present?
        @users = User.where("name like ?","%#{params[:name]}%").where("uid like ?","%#{params[:uid]}%").paginate(:page => params[:page], :per_page => 100)
    else
      if params[:name].present?
        @users = User.where("name like ?","%#{params[:name]}%").paginate(:page => params[:page], :per_page => 100)
      else
        if params[:uid].present?
          @users = User.where("uid like ?","%#{params[:uid]}%").paginate(:page => params[:page], :per_page => 100)
        else
          @users = User.paginate(:page => params[:page], :per_page => 100)
        end 
      end
    end
        
    if params[:sort].present?
      if params[:sort] == 'win-ratio'
        @users = @users.sort_by{|u| [-u.ratio_win, u.id]}
      else
        if params[:sort] == 'win-cont.'  
          @users = @users.sort_by{|u| [-u.continuous_win, u.id]}
        else
          if params[:sort] == 'loss-cont.'  
            @users = @users.sort_by{|u| [-u.continuous_loss, u.id]}
          end
        end  
      end
    end
    
    respond_to do |format|             
      format.html { render :index }        
      format.csv do        
        @data = users_to_csv(@users)
        render "data.csv.erb"                
      end            
    end
    
  end

  # GET /users/1
  # GET /users/1.json
  def show         
    
    @bets = Bet.where("user_id = ?",@user).sort_by{|b| [b.match.start]}
    @prizes = Prize.where("user_id = ?",@user)
    
    respond_to do |format|
      if params[:modal].present?        
        format.html { render :show_modal, layout: false }
      else
        format.html { render :show }
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
    @party = Config.find_by_key('PARTY').value.split(",")
    @gender = ["male","female"]
  end

  # GET /users/1/edit
  def edit
    @party = Config.find_by_key('PARTY').value.split(",")
    @gender = ["male","female"]
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def champion
    @teams = Team.all
    render layout: false
  end
  
  def top_goal_scorer
    @teams = Team.all        
    render layout: false
  end
  
  def update_champion
    user_bet_champion_end_time = DateTime.parse(Config.find_by_key('USER_BET_CHAMPION_END_TIME').value)    
    @user = User.find(session[:user_id])  
    respond_to do |format|
      if user_bet_champion_end_time.future?
        @user.update(user_champion_params)
      end      
      format.html { redirect_to :root }      
    end    
  end
  
  def update_top_goal_scorer
    user_bet_top_goal_scorer_end_time = DateTime.parse(Config.find_by_key('USER_BET_TOP_GOAL_SCORER_END_TIME').value)    
    @user = User.find(session[:user_id])  
    respond_to do |format|     
      if user_bet_top_goal_scorer_end_time.future?
        @user.update(user_top_goal_scorer_params)
      end       
      format.html { redirect_to :root }           
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:provider, :uid, :name, :email, :image, :admin, :team_id, :top_goal_scorer, :payment, :party, :nickname, :gender)
    end
    
    def user_champion_params
      params.require(:user).permit(:team_id)
    end
    
    def user_top_goal_scorer_params
      params.require(:user).permit(:top_goal_scorer)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :provider %>
    <%= form.text_field :provider, id: :user_provider %>
  </div>

  <div class="field">
    <%= form.label :uid %>
    <%= form.text_field :uid, id: :user_uid %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :user_image %>
  </div>
  
  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin, id: :user_admin %>
  </div>
  
  <div class="field">
    <%= form.label :payment %>
    <%= form.check_box :payment, id: :payment %>
  </div>
  
  <div class="field">
    <%= form.label :party %>
    <%= form.select(:party, @party, {:include_blank => true} ) %>
  </div>
  
  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, id: :nickname %>
  </div>
  
  <div class="field">
    <%= form.label :gender %>
    <%= form.select(:gender, @gender, {:include_blank => true} ) %>
  </div>
  
  <div class="field">
    <%= form.label :champion %>
    <%= form.collection_select(:team_id, Team.all, :id, :name, {:include_blank => true} ) %>
  </div>
  
  <div class="field">
    <%= form.label :top_goal_scorer %>
    <%= form.text_field :top_goal_scorer, id: :top_goal_scorer %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_search.html.erb
<%= form_tag(users_path, method: "get") do |form| %>
<div class="row">	
	<div class="col-md-4">
		<div class="form-group">
			<%= label_tag(:name) %>
			<%= text_field_tag(:name,nil, :class=>'form-control') %>
		</div>
	</div>
	<div class="col-md-4">
		<div class="form-group">
			<%= label_tag(:uid) %>
			<%= text_field_tag(:uid,nil, :class=>'form-control') %>
		</div>
	</div>	
	<div class="col-md-4">
		<div class="form-group">
			<%= label_tag(:sort) %>
			<%= select_tag :sort, options_for_select(["win-ratio","win-cont.", "loss-cont."]), :class=>'form-control', include_blank: true %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="actions">
			<%= submit_tag("Search", :class=>'btn btn-default') %>
			<%= submit_tag("Clear", :class=>'btn btn-default',:type => "reset") %>
		</div>
	</div>
</div>

<% end %>

app/views/users/champion.html.erb
<p id="notice">
	<%= notice %>
</p>

<%= form_with(model: @user, url: user_champion_edit_path, method: :put, local: true) do |form| %>
<div class="panel panel-default">
	<div class="panel-heading">
		Champion
	</div>
	<div class="panel-body">
		<div class="field">
			<%= form.label :champion %>
			<%= form.collection_select(:team_id, Team.all, :id, :name, {prompt: true, include_blank: true}) %>
		</div>
	</div>
</div>
<div class="actions">
	<%= form.submit %>
</div>
<% end %>

app/views/users/data.csv.erb
<%= @data %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice">
	<%= notice %>
</p>

<h1>Users</h1>

<div class="row">
	<div class="col-md-12">
		<%= render 'search' %>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<p align="right">
			Export : <%= link_to('<i class="fa fa-file-excel-o" aria-hidden="true"></i>'.html_safe, users_path(format: :csv)) %>
		</p>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Avatar</th>
					<th>UID</th>
					<th>Name</th>
					<th>Nickname</th>
					<th>Email</th>
					<th>Admin</th>
					<th>Payment</th>
					<th>Party</th>					
					<th>Champion</th>
					<th>Top goal scorer</th>
					<th>Win Ratio</th>
					<th>Win Cont.</th>
					<th>Loss Cont.</th>					
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= display_user(user) %></td>
					<td><%= user.uid %></td>
					<td><%= user.name %></td>
					<td><%= user.nickname %></td>
					<td><%= user.email %></td>					
					<td><%= user.admin %></td>
					<td><%= user.display_payment %></td>
					<td><%= user.party %></td>											
					<td><%= display_team(user.champion) %></td>
					<td><%= user.top_goal_scorer %></td>
					<td><%= user.ratio_win %></td>
					<td><%= user.continuous_win %></td>
					<td><%= user.continuous_loss %></td>
					<td> <%= link_to 'Show', user , :class => 'btn btn-default'%>
					<%= link_to 'Edit', edit_user_path(user) , :class => 'btn btn-default'%>
					<%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-danger'%> </td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<div class="row">	
	<div class="col-md-12">
		<%= link_to 'New User', new_user_path , :class => 'btn btn-primary' %>
	</div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%= @user.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @user.uid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Image:</strong>
  <%= @user.image %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @user.payment %>
</p>

<p>
  <strong>Party:</strong>
  <%= @user.party %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Champion:</strong>
  <%= @user.champion.nil? ? "":@user.champion.name %>
</p>

<p>
  <strong>Top goal scorer:</strong>
  <%= @user.top_goal_scorer %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show_modal.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Information</strong>
			</div>
			<div class="panel-body pre-scrollable">	
				<ul class="list-unstyled">
					<li><p><strong>Name : </strong><%= @user.display_name %></p></li>
					<li>
						<ul class="list-inline">
							<li><p><strong>Gender : </strong><%= display_gender(@user) %></p></li>
							<li><p><strong>Payment : </strong><%= @user.display_payment %></p></li>
							<li><p><strong>Party : </strong><%= @user.party %></p></li>
						</ul>
					</li>
					<li><p><strong>Champion : </strong><%= display_team(@user.champion) %></p></li>
					<li><p><strong>Top goal scorer : </strong><%= @user.top_goal_scorer %></p></li>
				</ul>								
			</div>
		</div>
	</div>
	<div class="col-md-6">
		
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<strong>Stat</strong>
					</div>
					<div class="panel-body pre-scrollable">
						<ul class="list-unstyled">
							<li>
								<ul class="list-inline">
										<li><p><strong>Rank : </strong><%= @user.rank %></p></li>
										<li><p><strong>P : </strong><%= @user.p %></p></li>
										<li><p><strong>PTS : </strong><%= @user.pts %></p></li>								
								</ul>	
							</li>
							<li>
								<ul class="list-inline">
									<li><p><strong>Win rate : </strong><%= "#{@user.ratio_win} %" %></p></li>
									<li><p><strong>Win cont. : </strong><%= "#{@user.continuous_win}" %></p></li>
									<li><p><strong>Loss cont. : </strong><%= "#{@user.continuous_loss}" %></p></li>
								</ul>
							</li>
						</ul>

					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<strong>Prizes : </strong><%= @prizes.size %> (<%= @prizes.inject(0){|sum,x| sum + x.price} %> baht)
					</div>
					<div class="panel-body pre-scrollable">						
						<p>
							<% @prizes.each do |prize| %>
							<span><%= display_prize(prize) %></span>
							<% end %>
						</p>						
					</div>
				</div>
			</div>
		</div>		
		
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Bets (<%= @bets.size %>)</strong>
			</div>
			<div class="panel-body pre-scrollable">
				<table class="table table-hover">
			<thead>
			    <tr class="active">
			      <th class="text-center">Match</th>
			      <th class="text-center">Information</th>
			      <th class="text-center">Result</th>			      
			      <th class="text-center">Bet</th>			      
			      <th class="text-center">Score</th>
			      <th colspan="3"></th>
			    </tr>
			</thead>
			<tbody>
				<% @bets.each do |bet| %>
				<tr>
					<td><%= display_match_description(bet.match) %></td>
					<td class="text-center"><%= display_match_versus(bet.match) %></td>										
					<td class="text-center"><%= display_match_result(bet.match) %></td>    					    		
        			<td class="text-center">
        				<% if bet.public? %>
        					<%= display_your_bet(bet) %>
        				<% else %>
        					<% if bet.owner?(User.find(session[:user_id]))%>
        						<%= display_your_bet(bet) %>	
							<% else %>
								<i class="fa fa-eye-slash fa-1x" aria-hidden="true"></i>        						
        					<% end %>
        				<% end %>
        			</td>
        			        					
        			<td class="text-right"><%= display_your_score(bet) %></td>        			
				</tr>
				<% end %>
			</tbody>
		</table>
			</div>
		</div>
	</div>
</div>

app/views/users/top_goal_scorer.html.erb
<p id="notice">
	<%= notice %>
</p>
<%= form_with(model: @user, url: user_top_goal_scorer_edit_path, method: :put, local: true) do |form| %>
<div class="panel panel-default">
	<div class="panel-heading">
		Top goal scorer
	</div>
	<div class="panel-body">
		<div class="field">
			<%= form.label :team %>
			<%= form.collection_select(:top_goal_scorer_team_id, Team.all, :id, :name, {prompt: true}) %>
		</div>
		<div class="field">
			<%= form.label :top_goal_scorer %>
			<%= form.select(:top_goal_scorer, {}) %>
		</div>
	</div>
</div>
<div class="actions">
	<%= form.submit %>
</div>
<% end %>
<script>
	$('#user_top_goal_scorer_team_id').on('change', function() {
		$("#user_top_goal_scorer").empty();
		$("#user_top_goal_scorer").hide();
		$.getJSON("teams/" + this.value + "/players.json", function(data) {
			$.each(data, function(key, value) {								
				var top_goal_scorer_key = value.name + ' (' + $("#user_top_goal_scorer_team_id :selected").text() + ')';
				var top_goal_scorer_value = value.name + ' (' + value.position + ')';
				$('#user_top_goal_scorer').append($("<option></option>").attr("value", top_goal_scorer_key).text(top_goal_scorer_value));
			});
			$("#user_top_goal_scorer").show();  
		});
	})
</script>