config/routes.rb
Rails.application.routes.draw do
 
  resources :sponsors
  resources :prizes
  get 'privacy/index', :as => :privacy
  get 'help/index', :as => :help

  resources :bets
  resources :matches
  resources :configs
  resources :groups
  resources :teams
  resources :users
  get '/overview/index'
  get '/sessions/login'
  
  get '/overview/bet', :as => :user_bet
  
  get '/matches/:id/random_bets'  => 'matches#random_bets', :as => :random_bets
  get '/matches/:id/random_result'  => 'matches#random_result', :as => :random_result
  
  get '/users/:id/champion'  => 'users#champion', :as => :user_champion
  get '/users/:id/top_goal_scorer'  => 'users#top_goal_scorer', :as => :user_top_goal_scorer
  put '/users/:id/champion'  => 'users#update_champion', :as => :user_champion_edit 
  put '/users/:id/top_goal_scorer'  => 'users#update_top_goal_scorer', :as => :user_top_goal_scorer_edit
  
  get '/teams/:id/players' => 'teams#players', :as => :team_players
  
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/signin_facebook' => 'sessions#new_facebook', :as => :signin_facebook
  get '/signin_google' => 'sessions#new_google', :as => :signin_google 
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'overview#index'
end

app/models/match.rb
class Match < ApplicationRecord    
  
  validates :title, :start, presence: true
  validates :title, length: { maximum: 64 }
  validates :description, :live, length: { maximum: 128 }      
  validate :validate_live
    
  belongs_to :left, :class_name => 'Team', :foreign_key => 'left_id', optional: true
  belongs_to :right, :class_name => 'Team', :foreign_key => 'right_id', optional: true
  
  has_many :prizes
  
  def display_title        
       return "#{self.id}-#{self.description} #{self.title} (#{self.display_versus})"
  end
  
  def display_versus
    if self.left.nil? || self.right.nil?
      return "left vs right"
    else
      return "#{self.left.name} vs #{self.right.name}"      
    end    
  end
  
  def final?
    return !self.result.nil?
  end  
  
  def lock?
    return self.start.past?
  end
  
  def random_bets(caller)
      logger.info "Random bets for match #{self.title} by #{caller.name}"                        
      users = User.all
      users.each do |user|        
        Bet.random(caller, user, self)        
      end            
  end
  
  def user_bet_count
    return Bet.where(match: self).length()
  end
  
  def total_bet_count
    return User.count()
  end
  
  def bet_statistic
    bets = Bet.where(match: self)
    left = 0
    draw = 0
    right = 0    
    bets.each do |bet|
      if bet.bet > 0
        right = right + 1
      else
        if bet.bet < 0
          left = left + 1
        else
          draw = draw + 1
        end 
      end
    end
    
    if bets.length > 0
      left_percent = left*100/bets.length
      draw_percent = draw*100/bets.length
      right_percent = right*100/bets.length
      return "#{left_percent}%, #{draw_percent}%, #{right_percent}%"
    else
      return "n/a, n/a, n/a"
    end            
    
  end
  
  private
  def validate_live
    support = ['amarin', 'gmm25', 'mcot9', 'nation22', 'nbt11', 'one', 'thaipbs', 'true4u', 'tv_thairath', 'tv_workpoint23', 'tv3', 'tv3family', 'tv3sd', 'tv5', 'tv7', 'tv8', 'pptv']
    if !self.live.nil?
      self.live.split(",").each do |live|
        if !support.include?(live)        
          errors.add(:match,"live channel #{live} not supported.")
          throw(:abort)
        end
      end
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :require_login_permission_and_admin, except: [:show]
  before_action :require_login_permission, only: [:show]
  before_action :set_match, only: [:show, :edit, :update, :destroy, :random_bets, :random_result]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.order(:start).paginate(:page => params[:page])
  end

  def bets_to_csv(bets)   
    csv_string = CsvShaper::Shaper.encode do |csv|      
      csv.headers do |header|
        header.columns :match, :user, :nickname, :gender, :payment, :bet, :bet_left_score, :bet_right_score, :yellow_card, :red_card, :own_goal, :extra_time, :penalty, :win?, :random?, :pts, :prizes
      end      
      bets.each do |bet|
        csv.row do |row|
          row.cell :match, bet.match.display_title
          row.cell :user, bet.user.name
          row.cell :nickname, bet.user.nickname
          row.cell :gender, bet.user.gender
          row.cell :payment, bet.user.display_payment       
          
          if bet.bet == 0
            row.cell :bet, "Draw"  
          else
            if bet.bet == -1
              row.cell :bet, bet.match.left.name
            else
              row.cell :bet, bet.match.right.name
            end
          end
                              
          row.cell :bet_left_score, bet.bet_left_score
          row.cell :bet_right_score, bet.bet_right_score
          row.cell :yellow_card, bet.yellow_card
          row.cell :red_card, bet.red_card
          row.cell :own_goal, bet.own_goal
          
          if bet.match.knockout?
            row.cell :extra_time, bet.extra_time
            row.cell :penalty, bet.penalty          
          end       
             
          if bet.updated_at > bet.match.start
            row.cell :random?, "Y"
          else
            row.cell :random?, "N"
          end
             
          row.cell :win?, bet.win?
          row.cell :pts, bet.pts
          row.cell :prizes, bet.user.prizes.size                      
        end
      end
    end
    return csv_string
  end
  
  # GET /matches/1
  # GET /matches/1.json
  def show                        
    
    @top5 = Bet.where(match: @match).sort_by{|b| [-b.pts, b.created_at]}[0..4] 
                        
    respond_to do |format|
      if params[:modal].present?        
        format.html { render :show_modal, layout: false }
      else
        format.html { render :show }
      end      
      format.csv do
        if @match.final?
          bets = Bet.where("match_id = ?", @match)
          @data = bets_to_csv(bets)
          render "data.csv.erb"
        else
          @data = "wating match result."
          render "data.csv.erb"
        end        
      end            
    end
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def random_bets
    caller = User.find(session[:user_id])
    @match.random_bets(caller)
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully random bets.' }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:title, :description, :live, :start, :knockout, :left_id, :right_id, :result, :left_score, :right_score, :yellow_card, :red_card, :own_goal, :extra_time, :penalty)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
<% if match.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

	<ul>
		<% match.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= form.label :title %>
	<%= form.text_field :title, id: :match_title %>
</div>

<div class="field">
	<%= form.label :description %>
	<%= form.text_field :description, id: :match_description %>
</div>

<div class="field">
	<%= form.label :live %>
	<%= form.text_field :live, id: :match_live %>
</div>

<div class="field">
	<%= form.label :start %>
	<%= form.datetime_select :start, id: :match_start %>
</div>

<div class="field">
	<%= form.label :knockout %>
	<%= form.check_box :knockout, id: :match_knockout %>
</div>

<div class="field">
	<%= form.label :left %>
	<%= form.collection_select(:left_id, Team.all, :id, :name, {prompt: true} ) %>
</div>

<div class="field">
	<%= form.label :right %>
	<%= form.collection_select(:right_id, Team.all, :id, :name, {prompt: true} ) %>
</div>

<div class="field">
	<%= form.label :result %>
	<%= form.number_field :result, id: :bet_result %>
</div>

<div class="field">
	<%= form.label :left_score %>
	<%= form.number_field :left_score, id: :match_left_score %>
</div>

<div class="field">
	<%= form.label :right_score %>
	<%= form.number_field :right_score, id: :match_right_score %>
</div>
<div class="field">
	<%= form.label :yellow_card %>
	<%= form.check_box :yellow_card, id: :yellow_card %>
</div>
<div class="field">
	<%= form.label :red_card %>
	<%= form.check_box :red_card, id: :red_card %>
</div>
<div class="field">
	<%= form.label :own_goal %>
	<%= form.check_box :own_goal, id: :own_goal %>
</div>
<div class="field">
	<%= form.label :penalty %>
	<%= form.check_box :penalty, id: :penalty %>
</div>
<div class="field">
	<%= form.label :extra_time %>
	<%= form.check_box :extra_time, id: :extra_time %>
</div>

<div class="actions">
	<%= form.submit %>
</div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice">
	<%= notice %>
</p>

<h1>Matches</h1>

<%= render 'search' %>

<div class="row">
	<div class="col-md-12">
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Title</th>
					<th>Description</th>
					<th>Start</th>
					<th>Knockout</th>
					<th>Left</th>
					<th>Right</th>
					<th>Locked?</th>
					<th>Result</th>
					<th>Left Score</th>
					<th>Right Score</th>
					<th>Bets</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @matches.each do |match| %>
				<tr class=<%= match.lock? ? ("danger") : ("success") %> >
					<td><%= match.title %></td>
					<td><%= match.description %></td>
					<td><%= match.start %></td>
					<td><%= match.knockout %></td>
					<td><%= display_team(match.left) %></td>
					<td><%= display_team(match.right) %></td>
					<td><%= match.lock? %></td>						
					<td><%= display_match_result(match) %></td>
					<td><%= match.left_score %></td>
					<td><%= match.right_score %></td>	
					<td><%= "#{match.user_bet_count}/#{match.total_bet_count}" %></td>
					<td><%= link_to 'Show', match , :class => 'btn btn-default'%>
					<%= link_to 'Edit', edit_match_path(match) , :class => 'btn btn-default'%>
					<%= link_to 'Bets', random_bets_path(match.id), :class => 'btn btn-default'%>
					<%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-danger'%></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<%= will_paginate @matches %>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<%= link_to 'New Match', new_match_path , :class => 'btn btn-primary' %>
	</div>
</div>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>
	<strong>Title:</strong>
	<%= @match.title %>
</p>

<p>
	<strong>Description:</strong>
	<%= @match.description %>
</p>

<p>
	<strong>Live:</strong>
	<% if @match.live.nil? %>
	<%= '<i class="fa fa-television fa-2x" aria-hidden="true"></i>'.html_safe %>
	<% else %>
	<% @match.live.split(",").each do |live| %>
	<%= image_tag "tv/#{live}.jpg", height: '30', :title => live %>
	<% end %>
	<% end %>
</p>

<p>
	<strong>Knockout:</strong>
	<%= @match.knockout %>
</p>

<p>
	<strong>Start:</strong>
	<%= @match.start %>
</p>

<p>
	<strong>Statistics:</strong>
	<%= "#{@match.bet_statistic}" %>
</p>
<table class="table table-bordered">
	<tr class="active">
		<th class="text-center">Bet</th>
		<th class="text-center">Result</th>
	</tr>
	<tr>
		<td><%= "Result (#{Config.find_by_key('BET_MAIN_FINAL_RESULT_SCORE').value} points)" %></td>
		<td class="text-center"><%= display_match_result(@match) %></td>
	</tr>
	<tr>
		<td><%= "Left Score (#{Config.find_by_key('BET_MAIN_LEFT_TEAM_SCORE').value} points)" %></td>
		<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.left_score %></td>
	</tr>
	<tr>
		<td><%= "Right Score (#{Config.find_by_key('BET_MAIN_RIGHT_TEAM_SCORE').value} points)" %></td>
		<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.right_score %></td>
	</tr>
	<tr>
		<td><%= "#{:yellow_card}? (Yes/No) more then #{Config.find_by_key('BET_MAIN_YELLOW_CARD_CONDITION').value} cards (#{Config.find_by_key('BET_MAIN_YELLOW_CARD_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_YELLOW_CARD_SCORE').value} points)" %></td>
		<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.yellow_card %></td>
	</tr>
	<tr>
		<td><%= "#{:red_card}? (Yes/No) (#{Config.find_by_key('BET_MAIN_RED_CARD_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_RED_CARD_SCORE').value} points)" %></td>
		<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.red_card %></td>
	</tr>
	<tr>
		<td><%= "#{:own_goal}? (Yes/No) (#{Config.find_by_key('BET_MAIN_OWN_GOAL_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_OWN_GOAL_SCORE').value} points)" %></td>
		<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.own_goal %></td>
	</tr>
	<% if @match.knockout? %>
	<tr>
		<td><%= "#{:extra_time}? (Yes/No) (#{Config.find_by_key('BET_MAIN_EXTRA_TIME_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_EXTRA_TIME_SCORE').value} points)" %></td>
		<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.extra_time %></td>
	</tr>
	<tr>
		<td><%= "#{:penalty} shootout after a drawn match? (Yes/No) (#{Config.find_by_key('BET_MAIN_PENALTY_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_PENALTY_SCORE').value} points)" %></td>
		<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.penalty %></td>
	</tr>
	<% end %>
</table>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>

app/views/matches/show_modal.html.erb
<p id="notice">
	<%= notice %>
</p>

<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Information</strong>
			</div>
			<div class="panel-body pre-scrollable">
				<p>
					<strong>Title:</strong>
					<%= @match.title %>
				</p>				
				<p>
					<strong>Live:</strong>
					<% if @match.live.nil? %>
					<%= '<i class="fa fa-television fa-2x" aria-hidden="true"></i>'.html_safe %>
					<% else %>
					<% @match.live.split(",").each do |live| %>
					<%= image_tag "tv/#{live}.jpg", height: '30', :title => live %>
					<% end %>
					<% end %>
				</p>
				<p>
					<strong>Knockout:</strong>
					<%= @match.knockout ? 'Yes':'No' %>
				</p>
				<p>
					<strong>Kick-off:</strong>
					<%= @match.start.strftime("%-d %-b %Y %H:%M:%S") %>
				</p>
				<p>
					<strong>Description:</strong>
					<%= @match.description %>
				</p>							
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<strong>Prizes</strong>
					</div>
					<div class="panel-body pre-scrollable">
						<p>
							<% @match.prizes.each do |prize| %>
							<span><%= display_prize(prize) %></span>
							<% end %>
						</p>
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<strong>Bets Stat</strong>
					</div>
					<div class="panel-body pre-scrollable">
						<p><strong>Result (L/D/R) : </strong>
							<%= @match.bet_statistic %>
						</p>
						<p><strong>Raw Data : </strong>	
						<% if @match.final? %>													
							<%= link_to('<i class="fa fa-file-excel-o" aria-hidden="true"></i>'.html_safe, match_path(format: :csv)) %>
						<% else %>
							n/a
						<% end %>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>Result</strong>
			</div>
			<div class="panel-body pre-scrollable">
				<table class="table table-bordered">
					<tr class="active">
						<th class="text-center">Bet</th>
						<th class="text-center">Result</th>
					</tr>
					<tr>
						<td><%= "Result (#{Config.find_by_key('BET_MAIN_FINAL_RESULT_SCORE').value} points)" %></td>
						<td class="text-center"><%= display_match_result(@match) %></td>
					</tr>
					<tr>
						<td><%= "Left Score (#{Config.find_by_key('BET_MAIN_LEFT_TEAM_SCORE').value} points)" %></td>
						<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.left_score %></td>
					</tr>
					<tr>
						<td><%= "Right Score (#{Config.find_by_key('BET_MAIN_RIGHT_TEAM_SCORE').value} points)" %></td>
						<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.right_score %></td>
					</tr>
					<tr>
						<td><%= "#{:yellow_card}? (Yes/No) more then #{Config.find_by_key('BET_MAIN_YELLOW_CARD_CONDITION').value} cards (#{Config.find_by_key('BET_MAIN_YELLOW_CARD_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_YELLOW_CARD_SCORE').value} points)" %></td>
						<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.yellow_card %></td>
					</tr>
					<tr>
						<td><%= "#{:red_card}? (Yes/No) (#{Config.find_by_key('BET_MAIN_RED_CARD_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_RED_CARD_SCORE').value} points)" %></td>
						<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.red_card %></td>
					</tr>
					<tr>
						<td><%= "#{:own_goal}? (Yes/No) (#{Config.find_by_key('BET_MAIN_OWN_GOAL_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_OWN_GOAL_SCORE').value} points)" %></td>
						<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.own_goal %></td>
					</tr>
					<% if @match.knockout? %>
					<tr>
						<td><%= "#{:extra_time}? (Yes/No) (#{Config.find_by_key('BET_MAIN_EXTRA_TIME_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_EXTRA_TIME_SCORE').value} points)" %></td>
						<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.extra_time %></td>
					</tr>
					<tr>
						<td><%= "#{:penalty} shootout after a drawn match? (Yes/No) (#{Config.find_by_key('BET_MAIN_PENALTY_SCORE').value}/#{Config.find_by_key('BET_MAIN_NO_PENALTY_SCORE').value} points)" %></td>
						<td class="text-center"><%= @match.result.nil? ? '<i class="fa fa-question fa-1x" aria-hidden="true"></i>'.html_safe : @match.penalty %></td>
					</tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>